# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AlertDialogSample
                                 A QGIS plugin
 sample program for making dialog
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-05
        copyright            : (C) 2022 by Yoichi Kayama
        email                : yoichi.kayama@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AlertDialogSample class from file AlertDialogSample.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AlertDialogSample import AlertDialogSample
    return AlertDialogSample(iface)
