# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AlertDialogSampleDialog
                                 A QGIS plugin
 sample program for making dialog
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-05
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Yoichi Kayama
        email                : yoichi.kayama@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QPropertyAnimation, pyqtProperty
from qgis.PyQt.QtGui import QColor,QPalette


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'alert_dialog_base.ui'))


class AlertDialog_Dialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, color1, color2, parent=None):

        

        """Constructor."""
        super(AlertDialog_Dialog, self).__init__(parent)

        #QWidget.__init__(self)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        color1 = QColor(255, 0, 0)
        color2 = QColor(0, 255, 0)

        self.color_anim = QPropertyAnimation(self, b'backColor')
        self.color_anim.setStartValue(color1)
        self.color_anim.setKeyValueAt(0.5, color2)
        self.color_anim.setEndValue(color1)
        self.color_anim.setDuration(1000)
        self.color_anim.setLoopCount(-1)
        self.color_anim.start()

    def getBackColor(self):
        return self.palette().color(QPalette.Background)

    def setBackColor(self, color):
        pal = self.palette()
        pal.setColor(QPalette.Background, color)
        self.setPalette(pal)

    backColor = pyqtProperty(QColor, getBackColor, setBackColor)
